"use client";

import Link from "next/link";
import { ArrowLeft, ArrowUpRight, GlobeSimple } from "@phosphor-icons/react";
import { projects } from "@/lib/projects";

export default function ProjectsPage() {
  return <main className="min-h-[100dvh]"><header className="mx-auto flex max-w-[1400px] items-center justify-between px-4 py-5 md:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm"><ArrowLeft size={18} weight="light" />Volver al portafolio</Link><span className="font-mono text-xs tracking-[0.16em] text-[var(--accent)]">SOFIA NEYRA</span></header><section className="mx-auto max-w-[1400px] px-4 pb-20 pt-12 md:px-8 md:pt-20"><h1 className="text-5xl font-medium tracking-[-0.055em] md:text-7xl">Mis proyectos</h1><p className="mt-6 max-w-xl leading-relaxed text-[var(--muted)]">Échale un vistazo a mi trabajo.</p><div className="mt-14 divide-y border-y">{projects.map((project) => <a key={project.slug} href={project.url} target="_blank" rel="noreferrer" className="group grid gap-3 py-5 transition-[transform,background-color] duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] hover:translate-x-2 hover:bg-[var(--surface)] md:grid-cols-[44px_1fr_auto] md:items-center"><span className="grid size-9 place-items-center rounded-full border text-[var(--accent)] transition-[transform,background-color,color] duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-110 group-hover:bg-[var(--accent)] group-hover:text-[var(--background)]"><GlobeSimple size={18} weight="light" /></span><h2 className="text-xl font-medium tracking-tight transition-transform duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:translate-x-1">{project.title}</h2><span className="inline-flex items-center gap-2 text-sm text-[var(--muted)] transition-[color,transform] duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:translate-x-1 group-hover:text-[var(--foreground)]">Ver sitio<ArrowUpRight size={18} weight="light" /></span></a>)}</div></section></main>;
}
