"use client";

import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Moon, Sun } from "@phosphor-icons/react";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import type { Locale, Project } from "@/lib/projects";
import { ProjectImage } from "@/components/project-image";

export function ProjectDetail({ project }: { project: Project }) {
  const [locale, setLocale] = useState<Locale>("es");
  const [theme, setTheme] = useState<"light" | "dark">("light");
  useEffect(() => { queueMicrotask(() => { setLocale((localStorage.getItem("sofia-locale") as Locale) || "es"); setTheme((localStorage.getItem("sofia-theme") as "light" | "dark") || "light"); }); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.lang = locale; }, [locale, theme]);
  const labels = locale === "es" ? { back: "Volver al portafolio", visit: "Visitar sitio", project: "Proyecto seleccionado", live: "Sitio publicado", note: "Esta ficha reúne el contexto visual esencial del proyecto y enlaza a su versión publicada." } : { back: "Back to portfolio", visit: "Visit website", project: "Selected project", live: "Published website", note: "This page keeps the project’s essential visual context and links to its published version." };
  return <main className="min-h-[100dvh]"><header className="mx-auto flex max-w-[1400px] items-center justify-between px-4 py-5 md:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm"><ArrowLeft size={18} weight="light" />{labels.back}</Link><div className="flex gap-2"><button onClick={() => setLocale(locale === "es" ? "en" : "es")} className="rounded-full border px-3 py-1.5 text-xs">{locale.toUpperCase()}</button><button onClick={() => setTheme(theme === "dark" ? "light" : "dark")} className="grid size-8 place-items-center rounded-full border" aria-label="Toggle color theme">{theme === "dark" ? <Sun size={16} /> : <Moon size={16} />}</button></div></header><article className="mx-auto max-w-[1400px] px-4 pb-16 pt-10 md:px-8 md:pt-20"><motion.p initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="font-mono text-xs tracking-[0.16em] text-[var(--accent)]">{labels.project}</motion.p><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 }} className="mt-5 text-5xl font-medium tracking-[-0.055em] md:text-7xl">{project.title}</motion.h1><div className="mt-12 grid gap-8 md:grid-cols-[1.25fr_.75fr]"><div className="relative aspect-[16/10] overflow-hidden rounded-[2rem] border bg-[var(--surface-muted)] p-6"><div className="h-7 w-full rounded-full border bg-[var(--surface)]" /><div className="mt-5 grid h-[calc(100%-48px)] grid-cols-[.35fr_.65fr] gap-5"><div className="rounded-2xl bg-[var(--accent-soft)]" /><div className="grid gap-5"><div className="rounded-2xl border bg-[var(--surface)]" /><div className="rounded-2xl bg-[var(--foreground)]/10" /></div></div><ProjectImage src={project.image} alt={`Captura del proyecto ${project.title}`} priority className="absolute inset-0 z-10 object-cover" /></div><div className="flex flex-col justify-between"><div><p className="font-mono text-xs tracking-[0.15em] text-[var(--muted)]">{labels.live}</p><p className="mt-5 text-xl leading-relaxed">{project.description[locale]}</p><p className="mt-5 leading-relaxed text-[var(--muted)]">{labels.note}</p><div className="mt-8 flex gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-full border px-3 py-1 text-xs">{tag}</span>)}</div></div><a href={project.url} target="_blank" rel="noreferrer" className="mt-10 inline-flex items-center gap-2 rounded-full bg-[var(--foreground)] px-5 py-3 text-sm font-medium text-[var(--background)]">{labels.visit}<ArrowUpRight size={18} weight="light" /></a></div></div></article></main>;
}
